name: Build docker images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker image tag'
        required: true

permissions:
  id-token: write
  contents: write
  packages: write

env:
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        make:
          - name: Build & Push WASM docker image
            image: wasm
            path: ./docker/namada-wasm
          - name: Build and Push Namada docker image
            image: namada
            path: ./docker/namada-build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/fraccaman/namada
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.make.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.make.path }}/Dockerfile
          push: true
          tags: ghcr.io/fraccaman:${{ matrix.make.image }}-${{ github.event.inputs.tag  }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ matrix.make.image }}-${{ github.event.inputs.tag  }}
          cache-to: type=inline
